# Configurações específicas para o ambiente de desenvolvimento
logging:
  level:
    com.carrefourbank: DEBUG
    org.springframework.jdbc.core: DEBUG
    org.springframework.web: DEBUG

spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/transaction_db
    username: ${DB_USER:transaction_user}
    password: ${DB_PASSWORD:transaction_password}

  cloud:
    gcp:
      project-id: ${GCP_PROJECT_ID:local-project}
      pubsub:
        # local: localhost:8085  |  docker: pubsub-emulator:8085
        emulator-host: ${PUBSUB_EMULATOR_HOST:localhost:8085}

management:
  endpoints:
    web:
      exposure:
        include: "*"
