# Configurações específicas para o ambiente de desenvolvimento
logging:
  level:
    com.carrefourbank: DEBUG
    org.springframework.jdbc.core: DEBUG
    org.springframework.web: DEBUG

# Configurações de banco de dados para desenvolvimento
spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5433}/dailybalance_db
    username: ${DB_USER:dailybalance_user}
    password: ${DB_PASSWORD:dailybalance_password}

  # Pub/Sub para ambiente local
  cloud:
    gcp:
      project-id: ${GCP_PROJECT_ID:local-project}
      pubsub:
        emulator-host: ${PUBSUB_EMULATOR_HOST:localhost:8085}

# Configurações de observabilidade para desenvolvimento
management:
  endpoints:
    web:
      exposure:
        include: "*"  # Expõe todos os endpoints para desenvolvimento